sudo: false
language: android

jdk:
  - oraclejdk7
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-20.0.0
    - android-23
    - addon-google_apis-google-23
    - extra-android-m2repository
    - extra-google-m2repository

before_install:
  - ./scripts/install-dependencies.rb

script:
  - ./scripts/install-robolectric.sh

after_success:
  - ./scripts/deploy-snapshot.sh

env:
  global:
    - secure: "AnsdYjHIvtLXrDMJmlf5FJhXJOW+aLSvsyXcGFLKse6EcwTSw8XnE4bGv2eSi2YWIwoHHCStIQbI0J02rkmUu9Z5oChxhOyGtCd8U4l1XciH2U7vJOJ/i9Auw5WgLM6x8HxgH6myhNrA9xrB4fcH+8WsDMf+qLqgvJQQjqQZQGM="
    - secure: "tKWNiNnT+WPmHNY1MtXTgwId9peXtsKQ5owdOfZqmEQYTSHVdya5Bt3CiK8U829Pa1ZBuF+9mnGufTbw0WfQM5TKlClDn4ciEJzz6ChS2cqO+6trsWy335nppU7pQsDE44Irju+E7Jh4kIjfnB2pWRhI2YAoAUhNyz39PawXsz8="

